"use client";
import * as React from 'react';import {lazy,Suspense} from 'react';
import {Plus,ArrowUpRight,Check,FileCode2,Folder,Play,Pause,RotateCcw} from 'lucide-react';
const Button=lazy(()=>import('../../../registry/ui/button').then(m=>({default:m.Button})));
const IconButton=lazy(()=>import('../../../registry/ui/icon-button').then(m=>({default:m.IconButton})));
const Badge=lazy(()=>import('../../../registry/ui/badge').then(m=>({default:m.Badge})));
const Avatar=lazy(()=>import('../../../registry/ui/avatar').then(m=>({default:m.Avatar})));
const Card=lazy(()=>import('../../../registry/ui/card').then(m=>({default:m.Card})));
import {CardHeader} from '../../../registry/ui/card';
import {CardTitle} from '../../../registry/ui/card';
import {CardDescription} from '../../../registry/ui/card';
import {CardAction} from '../../../registry/ui/card';
import {CardContent} from '../../../registry/ui/card';
import {CardFooter} from '../../../registry/ui/card';
const Separator=lazy(()=>import('../../../registry/ui/separator').then(m=>({default:m.Separator})));
const Skeleton=lazy(()=>import('../../../registry/ui/skeleton').then(m=>({default:m.Skeleton})));
const Spinner=lazy(()=>import('../../../registry/ui/spinner').then(m=>({default:m.Spinner})));
const Input=lazy(()=>import('../../../registry/ui/input').then(m=>({default:m.Input})));
const Textarea=lazy(()=>import('../../../registry/ui/textarea').then(m=>({default:m.Textarea})));
const Label=lazy(()=>import('../../../registry/ui/label').then(m=>({default:m.Label})));
const Checkbox=lazy(()=>import('../../../registry/ui/checkbox').then(m=>({default:m.Checkbox})));
const RadioGroup=lazy(()=>import('../../../registry/ui/radio-group').then(m=>({default:m.RadioGroup})));
const Switch=lazy(()=>import('../../../registry/ui/switch').then(m=>({default:m.Switch})));
const Select=lazy(()=>import('../../../registry/ui/select').then(m=>({default:m.Select})));
import {SelectValue} from '../../../registry/ui/select';
import {SelectTrigger} from '../../../registry/ui/select';
import {SelectContent} from '../../../registry/ui/select';
import {SelectItem} from '../../../registry/ui/select';
const Slider=lazy(()=>import('../../../registry/ui/slider').then(m=>({default:m.Slider})));
const ToggleGroup=lazy(()=>import('../../../registry/ui/toggle-group').then(m=>({default:m.ToggleGroup})));
const Tabs=lazy(()=>import('../../../registry/ui/tabs').then(m=>({default:m.Tabs})));
import {TabsList} from '../../../registry/ui/tabs';
import {TabsTrigger} from '../../../registry/ui/tabs';
import {TabsContent} from '../../../registry/ui/tabs';
const Accordion=lazy(()=>import('../../../registry/ui/accordion').then(m=>({default:m.Accordion})));
const Collapsible=lazy(()=>import('../../../registry/ui/collapsible').then(m=>({default:m.Collapsible})));
const Dialog=lazy(()=>import('../../../registry/ui/dialog').then(m=>({default:m.Dialog})));
import {DialogTrigger} from '../../../registry/ui/dialog';
import {DialogClose} from '../../../registry/ui/dialog';
import {DialogContent} from '../../../registry/ui/dialog';
import {DialogHeader} from '../../../registry/ui/dialog';
import {DialogFooter} from '../../../registry/ui/dialog';
import {DialogTitle} from '../../../registry/ui/dialog';
import {DialogDescription} from '../../../registry/ui/dialog';
const AlertDialog=lazy(()=>import('../../../registry/ui/alert-dialog').then(m=>({default:m.AlertDialog})));
const Sheet=lazy(()=>import('../../../registry/ui/sheet').then(m=>({default:m.Sheet})));
const Popover=lazy(()=>import('../../../registry/ui/popover').then(m=>({default:m.Popover})));
import {PopoverTrigger} from '../../../registry/ui/popover';
import {PopoverContent} from '../../../registry/ui/popover';
import {PopoverHeader} from '../../../registry/ui/popover';
import {PopoverTitle} from '../../../registry/ui/popover';
import {PopoverDescription} from '../../../registry/ui/popover';
const Tooltip=lazy(()=>import('../../../registry/ui/tooltip').then(m=>({default:m.Tooltip})));
const DropdownMenu=lazy(()=>import('../../../registry/ui/dropdown-menu').then(m=>({default:m.DropdownMenu})));
import {DropdownMenuTrigger} from '../../../registry/ui/dropdown-menu';
import {DropdownMenuSub} from '../../../registry/ui/dropdown-menu';
import {DropdownMenuContent} from '../../../registry/ui/dropdown-menu';
import {DropdownMenuItem} from '../../../registry/ui/dropdown-menu';
import {DropdownMenuLabel} from '../../../registry/ui/dropdown-menu';
import {DropdownMenuSeparator} from '../../../registry/ui/dropdown-menu';
import {DropdownMenuCheckboxItem} from '../../../registry/ui/dropdown-menu';
import {DropdownMenuSubTrigger} from '../../../registry/ui/dropdown-menu';
import {DropdownMenuSubContent} from '../../../registry/ui/dropdown-menu';
const ContextMenu=lazy(()=>import('../../../registry/ui/context-menu').then(m=>({default:m.ContextMenu})));
const NavigationMenu=lazy(()=>import('../../../registry/ui/navigation-menu').then(m=>({default:m.NavigationMenu})));
const Breadcrumb=lazy(()=>import('../../../registry/ui/breadcrumb').then(m=>({default:m.Breadcrumb})));
const Toast=lazy(()=>import('../../../registry/ui/toast').then(m=>({default:m.Toast})));
const Sidebar=lazy(()=>import('../../../registry/ui/sidebar').then(m=>({default:m.Sidebar})));
import {SidebarProvider} from '../../../registry/ui/sidebar';
import {SidebarHeader} from '../../../registry/ui/sidebar';
import {SidebarContent} from '../../../registry/ui/sidebar';
import {SidebarFooter} from '../../../registry/ui/sidebar';
import {SidebarGroup} from '../../../registry/ui/sidebar';
import {SidebarGroupLabel} from '../../../registry/ui/sidebar';
import {SidebarMenu} from '../../../registry/ui/sidebar';
import {SidebarMenuItem} from '../../../registry/ui/sidebar';
import {SidebarMenuButton} from '../../../registry/ui/sidebar';
import {SidebarMenuSub} from '../../../registry/ui/sidebar';
import {SidebarMenuSubItem} from '../../../registry/ui/sidebar';
import {SidebarMenuSubButton} from '../../../registry/ui/sidebar';
import {SidebarInset} from '../../../registry/ui/sidebar';
import {SidebarTrigger} from '../../../registry/ui/sidebar';
const Combobox=lazy(()=>import('../../../registry/ui/combobox').then(m=>({default:m.Combobox})));
const CommandPalette=lazy(()=>import('../../../registry/ui/command-palette').then(m=>({default:m.CommandPalette})));
const Calendar=lazy(()=>import('../../../registry/ui/calendar').then(m=>({default:m.Calendar})));
const DatePicker=lazy(()=>import('../../../registry/ui/date-picker').then(m=>({default:m.DatePicker})));
const DateRangePicker=lazy(()=>import('../../../registry/ui/date-range-picker').then(m=>({default:m.DateRangePicker})));
const TimePicker=lazy(()=>import('../../../registry/ui/time-picker').then(m=>({default:m.TimePicker})));
const FileUpload=lazy(()=>import('../../../registry/ui/file-upload').then(m=>({default:m.FileUpload})));
const OtpInput=lazy(()=>import('../../../registry/ui/otp-input').then(m=>({default:m.OtpInput})));
const PasswordInput=lazy(()=>import('../../../registry/ui/password-input').then(m=>({default:m.PasswordInput})));
const SearchInput=lazy(()=>import('../../../registry/ui/search-input').then(m=>({default:m.SearchInput})));
const TagInput=lazy(()=>import('../../../registry/ui/tag-input').then(m=>({default:m.TagInput})));
const FormField=lazy(()=>import('../../../registry/ui/form-field').then(m=>({default:m.FormField})));
const Pagination=lazy(()=>import('../../../registry/ui/pagination').then(m=>({default:m.Pagination})));
const DataTable=lazy(()=>import('../../../registry/ui/data-table').then(m=>({default:m.DataTable})));
const TreeView=lazy(()=>import('../../../registry/ui/tree-view').then(m=>({default:m.TreeView})));
import {ResizablePanelGroup} from '../../../registry/ui/resizable-panels';
import {ResizablePanel} from '../../../registry/ui/resizable-panels';
import {ResizableHandle} from '../../../registry/ui/resizable-panels';
const Stepper=lazy(()=>import('../../../registry/ui/stepper').then(m=>({default:m.Stepper})));
const EmptyState=lazy(()=>import('../../../registry/ui/empty-state').then(m=>({default:m.EmptyState})));
const Alert=lazy(()=>import('../../../registry/ui/alert').then(m=>({default:m.Alert})));
const Progress=lazy(()=>import('../../../registry/ui/progress').then(m=>({default:m.Progress})));
const TextReveal=lazy(()=>import('../../../registry/ui/text-reveal').then(m=>({default:m.TextReveal})));
const SplitText=lazy(()=>import('../../../registry/ui/split-text').then(m=>({default:m.SplitText})));
const RotatingText=lazy(()=>import('../../../registry/ui/rotating-text').then(m=>({default:m.RotatingText})));
const ScrambleText=lazy(()=>import('../../../registry/ui/scramble-text').then(m=>({default:m.ScrambleText})));
const NumberTicker=lazy(()=>import('../../../registry/ui/number-ticker').then(m=>({default:m.NumberTicker})));
const AnimatedCounter=lazy(()=>import('../../../registry/ui/animated-counter').then(m=>({default:m.AnimatedCounter})));
const Marquee=lazy(()=>import('../../../registry/ui/marquee').then(m=>({default:m.Marquee})));
const ScrollReveal=lazy(()=>import('../../../registry/ui/scroll-reveal').then(m=>({default:m.ScrollReveal})));
const StaggerGroup=lazy(()=>import('../../../registry/ui/stagger-group').then(m=>({default:m.StaggerGroup})));
const MagneticButton=lazy(()=>import('../../../registry/ui/magnetic-button').then(m=>({default:m.MagneticButton})));
const TiltCard=lazy(()=>import('../../../registry/ui/tilt-card').then(m=>({default:m.TiltCard})));
const SpotlightCard=lazy(()=>import('../../../registry/ui/spotlight-card').then(m=>({default:m.SpotlightCard})));
const AnimatedTabsIndicator=lazy(()=>import('../../../registry/ui/animated-tabs-indicator').then(m=>({default:m.AnimatedTabsIndicator})));
const SharedLayoutTransition=lazy(()=>import('../../../registry/ui/shared-layout-transition').then(m=>({default:m.SharedLayoutTransition})));
const ScrollProgress=lazy(()=>import('../../../registry/ui/scroll-progress').then(m=>({default:m.ScrollProgress})));
const GrainOverlay=lazy(()=>import('../../../registry/ui/grain-overlay').then(m=>({default:m.GrainOverlay})));
const DotGrid=lazy(()=>import('../../../registry/ui/dot-grid').then(m=>({default:m.DotGrid})));
const AnimatedGrid=lazy(()=>import('../../../registry/ui/animated-grid').then(m=>({default:m.AnimatedGrid})));
const GradientMesh=lazy(()=>import('../../../registry/ui/gradient-mesh').then(m=>({default:m.GradientMesh})));
const AuroraBackground=lazy(()=>import('../../../registry/ui/aurora-background').then(m=>({default:m.AuroraBackground})));
const SpotlightBackground=lazy(()=>import('../../../registry/ui/spotlight-background').then(m=>({default:m.SpotlightBackground})));
const BorderBeam=lazy(()=>import('../../../registry/ui/border-beam').then(m=>({default:m.BorderBeam})));
const RippleField=lazy(()=>import('../../../registry/ui/ripple-field').then(m=>({default:m.RippleField})));
const CursorTrail=lazy(()=>import('../../../registry/ui/cursor-trail').then(m=>({default:m.CursorTrail})));
const WebGLParticleField=lazy(()=>import('../../../registry/ui/webgl-particle-field').then(m=>({default:m.WebGLParticleField})));
const WebGLRibbonField=lazy(()=>import('../../../registry/ui/webgl-ribbon-field').then(m=>({default:m.WebGLRibbonField})));
const WebGLLiquidSurface=lazy(()=>import('../../../registry/ui/webgl-liquid-surface').then(m=>({default:m.WebGLLiquidSurface})));
const WebGLOrb=lazy(()=>import('../../../registry/ui/webgl-orb').then(m=>({default:m.WebGLOrb})));
const WebGLTerrain=lazy(()=>import('../../../registry/ui/webgl-terrain').then(m=>({default:m.WebGLTerrain})));
const WebGLImageDistortion=lazy(()=>import('../../../registry/ui/webgl-image-distortion').then(m=>({default:m.WebGLImageDistortion})));
const AreaChart=lazy(()=>import('../../../registry/ui/area-chart').then(m=>({default:m.AreaChart})));
const LineChart=lazy(()=>import('../../../registry/ui/line-chart').then(m=>({default:m.LineChart})));
const BarChart=lazy(()=>import('../../../registry/ui/bar-chart').then(m=>({default:m.BarChart})));
const StackedBarChart=lazy(()=>import('../../../registry/ui/stacked-bar-chart').then(m=>({default:m.StackedBarChart})));
const DonutChart=lazy(()=>import('../../../registry/ui/donut-chart').then(m=>({default:m.DonutChart})));
const RadialGauge=lazy(()=>import('../../../registry/ui/radial-gauge').then(m=>({default:m.RadialGauge})));
const Heatmap=lazy(()=>import('../../../registry/ui/heatmap').then(m=>({default:m.Heatmap})));
const Sparkline=lazy(()=>import('../../../registry/ui/sparkline').then(m=>({default:m.Sparkline})));
const LiveLineChart=lazy(()=>import('../../../registry/ui/live-line-chart').then(m=>({default:m.LiveLineChart})));
const ScatterChart=lazy(()=>import('../../../registry/ui/scatter-chart').then(m=>({default:m.ScatterChart})));
const MediaAside=lazy(()=>import('../../../registry/blocks/media-aside').then(m=>({default:m.MediaAside})));
const JournalBento=lazy(()=>import('../../../registry/blocks/journal-bento').then(m=>({default:m.JournalBento})));
const ArticleSidebar=lazy(()=>import('../../../registry/blocks/article-sidebar').then(m=>({default:m.ArticleSidebar})));
const EditorialFooter=lazy(()=>import('../../../registry/blocks/editorial-footer').then(m=>({default:m.EditorialFooter})));
const StudioFooter=lazy(()=>import('../../../registry/blocks/studio-footer').then(m=>({default:m.StudioFooter})));
const NewsletterFooter=lazy(()=>import('../../../registry/blocks/newsletter-footer').then(m=>({default:m.NewsletterFooter})));
const PlanComparison=lazy(()=>import('../../../registry/blocks/plan-comparison').then(m=>({default:m.PlanComparison})));
const FeatureComparison=lazy(()=>import('../../../registry/blocks/feature-comparison').then(m=>({default:m.FeatureComparison})));
const UsagePricing=lazy(()=>import('../../../registry/blocks/usage-pricing').then(m=>({default:m.UsagePricing})));
const EditorialHero=lazy(()=>import('../../../registry/blocks/editorial-hero').then(m=>({default:m.EditorialHero})));
const ProductDemoHero=lazy(()=>import('../../../registry/blocks/product-demo-hero').then(m=>({default:m.ProductDemoHero})));
const WebglHero=lazy(()=>import('../../../registry/blocks/webgl-hero').then(m=>({default:m.WebglHero})));
const LogoWall=lazy(()=>import('../../../registry/blocks/logo-wall').then(m=>({default:m.LogoWall})));
const FeatureGrid=lazy(()=>import('../../../registry/blocks/feature-grid').then(m=>({default:m.FeatureGrid})));
const AlternatingFeatureStory=lazy(()=>import('../../../registry/blocks/alternating-feature-story').then(m=>({default:m.AlternatingFeatureStory})));
const ProductComparison=lazy(()=>import('../../../registry/blocks/product-comparison').then(m=>({default:m.ProductComparison})));
const MetricsStrip=lazy(()=>import('../../../registry/blocks/metrics-strip').then(m=>({default:m.MetricsStrip})));
const TestimonialGrid=lazy(()=>import('../../../registry/blocks/testimonial-grid').then(m=>({default:m.TestimonialGrid})));
const TestimonialCarousel=lazy(()=>import('../../../registry/blocks/testimonial-carousel').then(m=>({default:m.TestimonialCarousel})));
const PricingTable=lazy(()=>import('../../../registry/blocks/pricing-table').then(m=>({default:m.PricingTable})));
const PricingComparison=lazy(()=>import('../../../registry/blocks/pricing-comparison').then(m=>({default:m.PricingComparison})));
const Faq=lazy(()=>import('../../../registry/blocks/faq').then(m=>({default:m.Faq})));
const NewsletterSignup=lazy(()=>import('../../../registry/blocks/newsletter-signup').then(m=>({default:m.NewsletterSignup})));
const ContactForm=lazy(()=>import('../../../registry/blocks/contact-form').then(m=>({default:m.ContactForm})));
const CtaSection=lazy(()=>import('../../../registry/blocks/cta-section').then(m=>({default:m.CtaSection})));
const MarketingNavigation=lazy(()=>import('../../../registry/blocks/marketing-navigation').then(m=>({default:m.MarketingNavigation})));
const MegaNavigation=lazy(()=>import('../../../registry/blocks/mega-navigation').then(m=>({default:m.MegaNavigation})));
const FloatingNavigation=lazy(()=>import('../../../registry/blocks/floating-navigation').then(m=>({default:m.FloatingNavigation})));
const TerrainHero=lazy(()=>import('../../../registry/blocks/terrain-hero').then(m=>({default:m.TerrainHero})));
const MarketingFooter=lazy(()=>import('../../../registry/blocks/marketing-footer').then(m=>({default:m.MarketingFooter})));
const ParticleHero=lazy(()=>import('../../../registry/blocks/particle-hero').then(m=>({default:m.ParticleHero})));
const LiquidHero=lazy(()=>import('../../../registry/blocks/liquid-hero').then(m=>({default:m.LiquidHero})));
const OrbHero=lazy(()=>import('../../../registry/blocks/orb-hero').then(m=>({default:m.OrbHero})));
const SilkHero=lazy(()=>import('../../../registry/blocks/silk-hero').then(m=>({default:m.SilkHero})));
const EclipseHero=lazy(()=>import('../../../registry/blocks/eclipse-hero').then(m=>({default:m.EclipseHero})));
const TunnelHero=lazy(()=>import('../../../registry/blocks/tunnel-hero').then(m=>({default:m.TunnelHero})));
const ConstellationHero=lazy(()=>import('../../../registry/blocks/constellation-hero').then(m=>({default:m.ConstellationHero})));
const DistortionHero=lazy(()=>import('../../../registry/blocks/distortion-hero').then(m=>({default:m.DistortionHero})));
const MediaHero=lazy(()=>import('../../../registry/blocks/media-hero').then(m=>({default:m.MediaHero})));
const TypographicHero=lazy(()=>import('../../../registry/blocks/typographic-hero').then(m=>({default:m.TypographicHero})));
const ShapeHero=lazy(()=>import('../../../registry/blocks/shape-hero').then(m=>({default:m.ShapeHero})));
const StudioHero=lazy(()=>import('../../../registry/blocks/studio-hero').then(m=>({default:m.StudioHero})));
const JournalHero=lazy(()=>import('../../../registry/blocks/journal-hero').then(m=>({default:m.JournalHero})));
const PosterHero=lazy(()=>import('../../../registry/blocks/poster-hero').then(m=>({default:m.PosterHero})));
const PortfolioHero=lazy(()=>import('../../../registry/blocks/portfolio-hero').then(m=>({default:m.PortfolioHero})));
const CollageHero=lazy(()=>import('../../../registry/blocks/collage-hero').then(m=>({default:m.CollageHero})));
const EditorialNavigation=lazy(()=>import('../../../registry/blocks/editorial-navigation').then(m=>({default:m.EditorialNavigation})));
const CommerceNavigation=lazy(()=>import('../../../registry/blocks/commerce-navigation').then(m=>({default:m.CommerceNavigation})));
const StudioNavigation=lazy(()=>import('../../../registry/blocks/studio-navigation').then(m=>({default:m.StudioNavigation})));
const ImmersiveLogin=lazy(()=>import('../../../registry/blocks/immersive-login').then(m=>({default:m.ImmersiveLogin})));
const RibbonLogin=lazy(()=>import('../../../registry/blocks/ribbon-login').then(m=>({default:m.RibbonLogin})));
const EditorialLogin=lazy(()=>import('../../../registry/blocks/editorial-login').then(m=>({default:m.EditorialLogin})));
const ApplicationShell=lazy(()=>import('../../../registry/blocks/application-shell').then(m=>({default:m.ApplicationShell})));
const WorkspaceNavigation=lazy(()=>import('../../../registry/blocks/workspace-navigation').then(m=>({default:m.WorkspaceNavigation})));
const AnalyticsOverview=lazy(()=>import('../../../registry/blocks/analytics-overview').then(m=>({default:m.AnalyticsOverview})));
const ActivityFeed=lazy(()=>import('../../../registry/blocks/activity-feed').then(m=>({default:m.ActivityFeed})));
const SearchableRecordsScreen=lazy(()=>import('../../../registry/blocks/searchable-records-screen').then(m=>({default:m.SearchableRecordsScreen})));
const RecordDetailPanel=lazy(()=>import('../../../registry/blocks/record-detail-panel').then(m=>({default:m.RecordDetailPanel})));
const KanbanBoard=lazy(()=>import('../../../registry/blocks/kanban-board').then(m=>({default:m.KanbanBoard})));
const TaskList=lazy(()=>import('../../../registry/blocks/task-list').then(m=>({default:m.TaskList})));
const CalendarSchedule=lazy(()=>import('../../../registry/blocks/calendar-schedule').then(m=>({default:m.CalendarSchedule})));
const OnboardingWizard=lazy(()=>import('../../../registry/blocks/onboarding-wizard').then(m=>({default:m.OnboardingWizard})));
const SignInForm=lazy(()=>import('../../../registry/blocks/sign-in-form').then(m=>({default:m.SignInForm})));
const SignUpForm=lazy(()=>import('../../../registry/blocks/sign-up-form').then(m=>({default:m.SignUpForm})));
const PasswordResetForm=lazy(()=>import('../../../registry/blocks/password-reset-form').then(m=>({default:m.PasswordResetForm})));
const ProfileSettings=lazy(()=>import('../../../registry/blocks/profile-settings').then(m=>({default:m.ProfileSettings})));
const TeamManagement=lazy(()=>import('../../../registry/blocks/team-management').then(m=>({default:m.TeamManagement})));
const BillingSettings=lazy(()=>import('../../../registry/blocks/billing-settings').then(m=>({default:m.BillingSettings})));
const NotificationCentre=lazy(()=>import('../../../registry/blocks/notification-centre').then(m=>({default:m.NotificationCentre})));
const CommandSearch=lazy(()=>import('../../../registry/blocks/command-search').then(m=>({default:m.CommandSearch})));
const ChatWorkspace=lazy(()=>import('../../../registry/blocks/chat-workspace').then(m=>({default:m.ChatWorkspace})));
const WorkspaceSidebar=lazy(()=>import('../../../registry/blocks/workspace-sidebar').then(m=>({default:m.WorkspaceSidebar})));
const RailSidebar=lazy(()=>import('../../../registry/blocks/rail-sidebar').then(m=>({default:m.RailSidebar})));
const InsetSidebar=lazy(()=>import('../../../registry/blocks/inset-sidebar').then(m=>({default:m.InsetSidebar})));
const UserSwitcher=lazy(()=>import('../../../registry/blocks/user-switcher').then(m=>({default:m.UserSwitcher})));
const OrganizationSwitcher=lazy(()=>import('../../../registry/blocks/organization-switcher').then(m=>({default:m.OrganizationSwitcher})));
const SSOLogin=lazy(()=>import('../../../registry/blocks/sso-login').then(m=>({default:m.SSOLogin})));
const SplitLogin=lazy(()=>import('../../../registry/blocks/split-login').then(m=>({default:m.SplitLogin})));
const WorkspaceLogin=lazy(()=>import('../../../registry/blocks/workspace-login').then(m=>({default:m.WorkspaceLogin})));
export function Demo({slug,customization={}}:{slug:string;customization?:{secondaryImageSrc?:string;secondaryImageAlt?:string;copy?:Record<string,string>;artworkText?:string;title?:string;description?:string;actionLabel?:string;brand?:string;imageSrc?:string;imageAlt?:string;artwork?:{color?:string;speed?:number}}}){const [showArchived,setShowArchived]=React.useState<boolean|"indeterminate">(true);const [notice,setNotice]=React.useState('');const [scenePaused,setScenePaused]=React.useState(false);const [sceneSpeed,setSceneSpeed]=React.useState(1);const [sceneColor,setSceneColor]=React.useState<string|undefined>(undefined);const [count,setCount]=React.useState(128);const [draft,setDraft]=React.useState('');const [searchTerm,setSearchTerm]=React.useState('');const [buttonBusy,setButtonBusy]=React.useState(false);const [progress,setProgress]=React.useState(0);const [progressRunning,setProgressRunning]=React.useState(false);React.useEffect(()=>{if(!buttonBusy)return;const timer=setTimeout(()=>{setButtonBusy(false);setNotice('Project published.');},900);return()=>clearTimeout(timer);},[buttonBusy]);React.useEffect(()=>{if(!progressRunning)return;if(progress>=100){setProgressRunning(false);return;}const timer=setTimeout(()=>setProgress(v=>Math.min(100,v+4)),200);return()=>clearTimeout(timer);},[progressRunning,progress]);const actions=[{label:'Duplicate',onSelect:()=>setNotice('A copy is ready.')},{label:'Archive',onSelect:()=>setNotice('Moved to archive.')}];const tabs=[{value:'design',label:'Design',content:'Make it feel like something.'},{value:'build',label:'Build',content:'Give a good idea a useful shape.'},{value:'share',label:'Share',content:'Put it into the world.'}];function render(){switch(slug){case 'button': return <div className="grid w-full max-w-lg gap-6"><div className="flex items-center justify-between border-b border-border pb-5"><div><h3 className="text-lg font-semibold">Project actions</h3><p className="mt-1 text-sm text-muted-foreground">Website refresh · Draft</p></div><Badge>Draft</Badge></div><div className="flex flex-wrap items-center gap-3"><Button loading={buttonBusy} onClick={()=>setButtonBusy(true)}><Plus size={16}/>Publish project</Button><Button variant="outline" onClick={()=>setNotice('Draft saved.')}>Save draft</Button><Button variant="ghost" onClick={()=>setNotice('Preview selected.')}>Preview <ArrowUpRight size={15}/></Button></div><div className="flex flex-wrap items-center gap-3"><Button size="sm" variant="secondary" onClick={()=>setNotice('Invitation link copied in this example.')}>Invite member</Button><Button size="sm" variant="danger" onClick={()=>setNotice('Archive action selected.')}>Archive</Button><Button size="sm" disabled>Up to date <Check size={14}/></Button></div></div>;
case 'icon-button': return <div className="flex items-center gap-5"><IconButton label="Add item" onClick={()=>setNotice('Item added')}><Plus size={18}/></IconButton><div><p className="font-medium">One small action.</p><p className="mt-1 text-sm text-muted-foreground">A new idea starts here.</p></div></div>;
case 'badge': return <div className="grid max-w-md gap-7"><h3 className="text-2xl">A status worth noticing.</h3><div className="flex flex-wrap gap-3"><Badge tone="positive">● Live</Badge><Badge tone="accent">In review</Badge><Badge tone="warning">Needs attention</Badge><Badge>Draft</Badge></div><p className="text-sm text-muted-foreground">Small signals. Clear next steps.</p></div>;
case 'avatar': return <div className="grid justify-items-center gap-6"><div className="flex -space-x-3">{['AM','JL','SK','RT'].map((person,i)=><Avatar key={person} alt={['Alex Morgan','Jamie Lee','Sam Kim','Rory Tate'][i]} fallback={person} className="size-14 border-4 border-background bg-muted text-base"/>)}</div><div className="text-center"><h3 className="text-2xl">Better, together.</h3><p className="mt-2 text-sm text-muted-foreground">Four people. One shared idea.</p></div></div>;
case 'card': return <Card><CardHeader><CardTitle>A little room to think.</CardTitle><CardDescription>A considered surface for whatever comes next.</CardDescription><CardAction><Badge>Draft</Badge></CardAction></CardHeader><CardContent><FormField label="Project name"><Input placeholder="Field notes"/></FormField></CardContent><CardFooter><Button onClick={()=>setNotice("Project created.")}>Create project</Button><Button variant="outline">Cancel</Button></CardFooter></Card>;
case 'separator': return <div className="grid w-full max-w-sm gap-5"><div className="flex justify-between"><h3 className="text-xl">Your workspace</h3><Badge>Personal</Badge></div><Separator/><div className="flex justify-between text-sm"><span>Projects</span><span className="text-muted-foreground">12</span></div><div className="flex justify-between text-sm"><span>Collaborators</span><span className="text-muted-foreground">4</span></div></div>;
case 'skeleton': return <div className="grid w-full max-w-sm gap-5"><Skeleton className="h-40 rounded-xl"/><div className="flex items-center gap-4"><Skeleton className="size-11 rounded-full"/><div className="grid flex-1 gap-3"><Skeleton className="w-3/4"/><Skeleton className="w-1/2"/></div></div><p className="text-xs text-muted-foreground">Making room for the next good thing.</p></div>;
case 'spinner': return <div className="flex items-center gap-5"><Spinner className="size-8"/><div><h3 className="text-xl">Bringing it together.</h3><p className="mt-1 text-sm text-muted-foreground">Your workspace is getting ready.</p></div></div>;
case 'input': return <div className="grid w-full max-w-sm gap-6"><h3 className="text-2xl">Give it a name.</h3><FormField label="Project name" hint="You can change this whenever you like."><Input placeholder="e.g. The next chapter"/></FormField><FormField label="Workspace URL"><div className="flex items-center rounded-lg border border-border px-3"><span className="shrink-0 whitespace-nowrap text-sm text-muted-foreground">studio.app /</span><Input className="border-0 bg-transparent shadow-none focus-visible:ring-0" aria-label="Workspace slug" defaultValue="field-notes"/></div></FormField></div>;
case 'textarea': return <div className="w-full max-w-lg"><div className="mb-4 flex items-center gap-3"><Avatar alt="Alex Morgan" fallback="AM" className="size-8"/><div><h3 className="text-sm font-semibold">Add a project update</h3><p className="text-xs text-muted-foreground">Shared with your team</p></div></div><div className="overflow-hidden rounded-xl border border-border focus-within:border-primary/50 focus-within:ring-3 focus-within:ring-primary/8"><Textarea aria-label="Project description" placeholder="What changed? What’s next?" maxLength={500} value={draft} onChange={e=>setDraft(e.target.value)} className="min-h-36 resize-none border-0 bg-transparent shadow-none focus-visible:ring-0"/><div className="flex items-center justify-between border-t border-border/50 bg-muted/20 px-3 py-2"><span className="text-xs text-muted-foreground tabular-nums">{draft.length} / 500</span><Button size="sm" disabled={!draft.trim()} onClick={()=>{setNotice('Update posted: '+draft);setDraft('');}}>Post update <ArrowUpRight size={14}/></Button></div></div></div>;
case 'label': return <div className="grid gap-2"><Label htmlFor="example-label">Project name</Label><input id="example-label" className="rounded border border-border p-2" placeholder="Field notes"/></div>;
case 'checkbox': return <div className="grid w-full max-w-sm gap-5"><h3 className="text-2xl">Before we go live.</h3>{['Add the finishing touches','Check the small screen','Share it with the team'].map((text,i)=><label key={text} className="flex items-center gap-3 border-b border-border pb-4 text-sm"><Checkbox defaultChecked={i===0}/>{text}</label>)}</div>;
case 'radio-group': return <RadioGroup defaultValue="balanced" aria-label="Density" options={[{label:'Comfortable',value:'comfortable'},{label:'Balanced',value:'balanced'},{label:'Compact',value:'compact'}]}/>;
case 'switch': return <div className="grid w-full max-w-sm gap-6"><div><h3 className="text-2xl">Keep your focus.</h3><p className="mt-2 text-sm text-muted-foreground">A quieter workspace, on your terms.</p></div>{[{name:'Focus mode',hint:'Make a little room to think.',on:true},{name:'Project updates',hint:'Only the changes that matter.',on:true},{name:'Weekly roundup',hint:'The whole picture, once a week.',on:false}].map(o=><label key={o.name} className="flex items-center justify-between gap-6 border-b border-border pb-5"><div><span className="text-sm font-medium">{o.name}</span><p className="mt-1 text-xs text-muted-foreground">{o.hint}</p></div><Switch defaultChecked={o.on}/></label>)}</div>;
case 'select': return <Select><SelectTrigger aria-label="Choose a discipline"><SelectValue placeholder="Choose a discipline"/></SelectTrigger><SelectContent><SelectItem value="design">Design</SelectItem><SelectItem value="engineering">Engineering</SelectItem><SelectItem value="both">Everything in between</SelectItem></SelectContent></Select>;
case 'slider': return <div className="grid min-w-0 w-full max-w-sm gap-8"><div className="flex items-end justify-between"><h3 className="text-3xl">Set the tone.</h3><span className="text-xs text-muted-foreground">Ambient radio</span></div><div className="flex h-20 min-w-0 items-center justify-center gap-1 sm:gap-1.5" aria-hidden="true">{Array.from({length:32},(_,i)=><span key={i} className="w-1.5 rounded-full bg-primary" style={{height:12+Math.abs(Math.sin(i*.8))*55}}/>)}</div><Slider label="Volume" defaultValue={[65]}/><div className="flex justify-between text-xs text-muted-foreground"><span>A little quieter</span><span>Turn it up</span></div></div>;
case 'toggle-group': return <ToggleGroup type="single" defaultValue="week" aria-label="Period" options={[{label:'Day',value:'day'},{label:'Week',value:'week'},{label:'Month',value:'month'}]}/>;
case 'tabs': return <Tabs defaultValue="design"><TabsList aria-label="Workflow">{tabs.map(t=><TabsTrigger key={t.value} value={t.value}>{t.label}</TabsTrigger>)}</TabsList>{tabs.map(t=><TabsContent key={t.value} value={t.value}>{t.content}</TabsContent>)}</Tabs>;
case 'accordion': return <Accordion type="single" collapsible items={[{value:'one',title:'What makes a good component?',content:'A clear purpose, thoughtful defaults, and room to make it yours.'},{value:'two',title:'Can I change it?',content:'The source is yours to adapt under your distribution licence.'}]}/>;
case 'collapsible': return <div className="w-full max-w-md"><Collapsible title="Changed files · 3" defaultOpen>{["components/button.tsx","styles/theme.css","tests/controls.spec.ts"].map((file,i)=><div key={file} className="flex items-center gap-2 py-2 text-sm"><FileCode2 size={15} className="shrink-0 text-muted-foreground"/><span className="min-w-0 flex-1 truncate font-mono text-xs">{file}</span><span className="text-xs text-primary">+{[24,8,16][i]}</span></div>)}</Collapsible></div>;
case 'dialog': return <Dialog><DialogTrigger asChild><Button>Open dialog</Button></DialogTrigger><DialogContent showClose={false}><DialogHeader><DialogTitle>Make it yours.</DialogTitle><DialogDescription>Give your project a name before you begin.</DialogDescription></DialogHeader><FormField label="Project name"><Input placeholder="Field notes"/></FormField><DialogFooter><DialogClose asChild><Button variant="outline">Close</Button></DialogClose></DialogFooter></DialogContent></Dialog>;
case 'alert-dialog': return <AlertDialog trigger={<Button variant="danger">Delete draft</Button>} title="Delete this draft?" description="This example asks for confirmation. No real data is deleted."/>;
case 'sheet': return <Sheet trigger={<Button variant="outline">Open details</Button>} title="Project details" description="Website refresh · PRJ-102"><div className="grid gap-6"><FormField label="Project name"><Input defaultValue="Website refresh"/></FormField><FormField label="Status"><Select label="Status" defaultValue="progress" options={[{label:"In progress",value:"progress"},{label:"In review",value:"review"},{label:"Complete",value:"complete"}]}/></FormField><FormField label="Notes"><Textarea defaultValue="Explore a clearer homepage direction and bring the component previews up to date."/></FormField><Button onClick={()=>setNotice("Project details saved.")}>Save changes</Button></div></Sheet>;
case 'popover': return <Popover><PopoverTrigger asChild><Button variant="outline">Project notes</Button></PopoverTrigger><PopoverContent><PopoverHeader><PopoverTitle>A small reminder</PopoverTitle><PopoverDescription>Leave room for the unexpected.</PopoverDescription></PopoverHeader></PopoverContent></Popover>;
case 'tooltip': return <Tooltip content="Save your current work"><Button variant="outline">Hover or focus me</Button></Tooltip>;
case 'dropdown-menu': return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline">Project actions ↓</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuLabel>Project</DropdownMenuLabel>{actions.map(action=><DropdownMenuItem key={action.label} onSelect={action.onSelect}>{action.label}</DropdownMenuItem>)}<DropdownMenuSeparator/><DropdownMenuCheckboxItem checked={showArchived} onCheckedChange={setShowArchived}>Show archived</DropdownMenuCheckboxItem><DropdownMenuSub><DropdownMenuSubTrigger>Move to</DropdownMenuSubTrigger><DropdownMenuSubContent><DropdownMenuItem onSelect={()=>setNotice("Moved to Personal.")}>Personal</DropdownMenuItem><DropdownMenuItem onSelect={()=>setNotice("Moved to Team.")}>Team</DropdownMenuItem></DropdownMenuSubContent></DropdownMenuSub></DropdownMenuContent></DropdownMenu>;
case 'context-menu': return <ContextMenu trigger={<div tabIndex={0} className="rounded-xl border border-dashed border-border p-10 text-sm">Right-click for actions</div>} items={actions}/>;
case 'navigation-menu': return <NavigationMenu items={[{label:'Components',href:'/components'},{label:'Blocks',href:'/blocks'},{label:'Templates',href:'/templates'}]}/>;
case 'breadcrumb': return <Breadcrumb items={[{label:'Library',href:'/components'},{label:'Foundations',href:'/components?category=foundations'},{label:'Breadcrumb'}]}/>;
case 'toast': return <Toast title="Changes saved" description="Your project is ready for its next chapter."/>;
case 'sidebar': return <SidebarProvider className="overflow-hidden rounded-xl border border-border"><Sidebar><SidebarHeader><span className="block truncate px-3 py-2 font-semibold">North Studio</span></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarMenu><SidebarMenuItem><SidebarMenuButton asChild isActive><a href="#overview"><Folder/><span>Overview</span></a></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton asChild><a href="#projects"><FileCode2/><span>Projects</span></a></SidebarMenuButton><SidebarMenuSub>{["Website refresh","Design system","Mobile app"].map(name=><SidebarMenuSubItem key={name}><SidebarMenuSubButton asChild><a href={"#"+name.toLowerCase().replaceAll(" ","-")}><span>{name}</span></a></SidebarMenuSubButton></SidebarMenuSubItem>)}</SidebarMenuSub></SidebarMenuItem></SidebarMenu></SidebarGroup><SidebarGroup><SidebarGroupLabel>Resources</SidebarGroupLabel><SidebarMenu>{["Documentation","Team","Settings"].map(name=><SidebarMenuItem key={name}><SidebarMenuButton asChild><a href={"#"+name.toLowerCase()}><Folder/><span>{name}</span></a></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><span className="block truncate px-3 text-xs">alex@north.example</span></SidebarFooter></Sidebar><SidebarInset><header className="flex items-center gap-3 border-b border-border p-4"><SidebarTrigger/><span className="text-sm">Workspace</span></header><div className="p-6"><h1 className="text-2xl">Built from your own pieces.</h1><p className="mt-3 text-sm text-muted-foreground">Add groups, nested links, custom headers, and account controls using children.</p></div></SidebarInset></SidebarProvider>;
case 'combobox': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Choose your starting point.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">The right tools for the way you work.</p></div><Combobox options={[{label:'React',value:'react',description:'Build interactive interfaces'},{label:'Next.js',value:'next',description:'React with server rendering'},{label:'Vite',value:'vite',description:'A fast development toolchain'},{label:'Astro',value:'astro',description:'Content-driven websites'},{label:'Remix',value:'remix',description:'Full-stack web applications'}]} label="Choose framework"/></div>;
case 'command-palette': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">One shortcut away.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Find your next action without losing your place.</p></div><CommandPalette items={[{label:"Create a project",group:"Workspace",shortcut:"⌘ N",onSelect:()=>setNotice("Create project selected.")},{label:"Find a teammate",group:"Workspace",onSelect:()=>setNotice("Team search selected.")},{label:"Open settings",group:"Navigation",shortcut:"⌘ ,",onSelect:()=>setNotice("Settings selected.")},{label:"View archive",group:"Navigation",onSelect:()=>setNotice("Archive selected.")}]}/></div>;
case 'calendar': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Make a little time.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">A day for the next good idea.</p></div><Calendar defaultValue="2026-09-08"/></div>;
case 'date-picker': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Put it on the calendar.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Set a launch date you can work toward.</p></div><DatePicker/></div>;
case 'date-range-picker': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">See the whole stretch.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Choose the window for your next project.</p></div><DateRangePicker/></div>;
case 'time-picker': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Meet in the morning.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Find a time that works for everyone.</p></div><TimePicker defaultValue="09:30"/></div>;
case 'file-upload': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Bring your ideas.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Drop in your reference images, sketches, or brief.</p></div><FileUpload accept="image/*,.pdf" multiple/></div>;
case 'otp-input': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">A quick check.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Enter the six-digit code to continue this demo.</p></div><OtpInput/></div>;
case 'password-input': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Keep it between us.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">A strong password is a good place to start.</p></div><PasswordInput placeholder="Your password"/></div>;
case 'search-input': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Find the thing.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Projects, notes, and the details you nearly forgot.</p></div><div><SearchInput value={searchTerm} onValueChange={setSearchTerm} placeholder="Search projects…"/><div className="mt-3 overflow-hidden rounded-lg border border-border">{["Website refresh","Brand guidelines","Component library"].filter(t=>t.toLowerCase().includes(searchTerm.toLowerCase())).map(t=><button key={t} onClick={()=>setNotice(t+" opened.")} className="flex w-full items-center gap-3 border-b border-border/50 px-3 py-3 text-left text-sm last:border-0 hover:bg-muted"><Folder size={15} className="text-muted-foreground"/>{t}<ArrowUpRight size={13} className="ml-auto text-muted-foreground"/></button>)}{!["Website refresh","Brand guidelines","Component library"].some(t=>t.toLowerCase().includes(searchTerm.toLowerCase()))&&<p className="p-5 text-sm text-muted-foreground">No projects found.</p>}</div></div></div>;
case 'tag-input': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">A little more organised.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Give your next idea a few useful labels.</p></div><TagInput defaultValue={['Design','Play']}/></div>;
case 'form-field': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Start something new.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Give your workspace a name you will remember.</p></div><FormField label="Project name" hint="Something you’ll recognise later."><Input placeholder="Field notes"/></FormField></div>;
case 'pagination': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">There is more to explore.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Browse the whole collection, at your own pace.</p></div><Pagination totalPages={8}/></div>;
case 'data-table': return <div className="w-full max-w-2xl"><div className="mb-7"><h3 className="text-2xl tracking-tight">Work in motion.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Three projects, from first thoughts to finished details.</p></div><DataTable selectable data={[{name:'Field notes',status:'Active',tasks:12},{name:'New perspective',status:'In review',tasks:8},{name:'Little things',status:'Done',tasks:24}]} columns={[{accessorKey:'name',header:'Project'},{accessorKey:'status',header:'Status',cell:c=><Badge tone={c.getValue()==='Done'?'positive':c.getValue()==='Active'?'accent':'neutral'}>{String(c.getValue())}</Badge>},{accessorKey:'tasks',header:'Tasks'}]}/></div>;
case 'tree-view': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Everything in its place.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">A clear path through your source.</p></div><TreeView nodes={[{id:'src',label:'Source',children:[{id:'components',label:'Components',children:[{id:'button',label:'button.tsx'},{id:'card',label:'card.tsx'}]},{id:'theme',label:'theme.css'}]}]} onSelect={n=>setNotice(n.label+' selected')}/></div>;
case 'resizable-panels': return <div className="w-full max-w-2xl"><div className="mb-7"><h3 className="text-2xl tracking-tight">Space that works for you.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Adjust the balance with a pointer or the arrow keys.</p></div><ResizablePanelGroup><ResizablePanel defaultSize={25} minSize={15}>Navigation</ResizablePanel><ResizableHandle aria-label="Resize navigation"/><ResizablePanel defaultSize={50} minSize={20}>Your workspace. Drag a divider or focus it and use arrow keys.</ResizablePanel><ResizableHandle aria-label="Resize inspector"/><ResizablePanel defaultSize={25} minSize={15}>Inspector</ResizablePanel></ResizablePanelGroup></div>;
case 'stepper': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">One thing at a time.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">A few small steps to make yourself at home.</p></div><Stepper steps={['Your details','Workspace','Ready']} current={1}/></div>;
case 'empty-state': return <EmptyState action={<Button onClick={()=>setNotice('Your first idea starts here.')}>Create an idea</Button>}/>;
case 'alert': return <Alert title="Everything is up to date.">Your changes have been saved on this device.</Alert>;
case 'progress': return <div className="w-full max-w-sm"><div className="mb-7"><h3 className="text-2xl tracking-tight">Getting there.</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">The next release is taking shape.</p></div><div className="grid gap-4"><div className="flex items-center justify-between text-sm"><span>{progress===100?"Export complete":progressRunning?"Preparing export…":progress>0?"Export paused":"Ready to export"}</span><span className="font-mono tabular-nums">{progress}%</span></div><Progress value={progress} label="Export progress" showLabel={false}/><div className="flex gap-2"><Button size="sm" disabled={progress===100} onClick={()=>setProgressRunning(v=>!v)}>{progressRunning?<Pause size={14}/>:<Play size={14}/>} {progressRunning?"Pause":progress>0?"Resume":"Start export"}</Button><Button size="sm" variant="ghost" aria-label="Reset progress" onClick={()=>{setProgressRunning(false);setProgress(0);}}><RotateCcw size={14}/></Button></div><p className="text-xs text-muted-foreground">Simulated export · try pausing halfway through.</p></div></div>;
case 'text-reveal': return <div className="w-full rounded-xl bg-accent px-7 py-14 text-foreground md:px-12 md:py-20"><TextReveal className="block max-w-xl font-display text-5xl font-medium leading-[1.03] tracking-tight md:text-7xl">Less noise. More feeling.</TextReveal><p className="mt-8 text-sm">A new perspective, one word at a time.</p></div>;
case 'split-text': return <div className="w-full rounded-xl bg-foreground px-7 py-14 text-background md:px-12 md:py-20"><SplitText className="block font-display text-5xl font-medium leading-none tracking-tight md:text-7xl">Stay curious.</SplitText><p className="mt-8 text-sm opacity-70">Good ideas start with a little movement.</p></div>;
case 'rotating-text': return <div className="w-full rounded-xl bg-muted p-8 md:p-14"><div className="font-display text-5xl font-medium leading-tight tracking-tight md:text-6xl">A place for<br/><RotatingText words={['bold ideas.','small details.','your next thing.']} className="text-primary"/></div><p className="mt-9 text-sm text-muted-foreground">Keep making room.</p></div>;
case 'scramble-text': return <div className="w-full rounded-xl bg-foreground p-8 text-accent md:p-14"><ScrambleText className="font-display text-4xl font-medium tracking-tight md:text-6xl">Expect the unexpected.</ScrambleText><div className="mt-10 flex justify-between border-t border-current pt-4 text-xs"><span>Order from a little chaos.</span><span>Jez / Motion</span></div></div>;
case 'number-ticker': return <div className="grid w-full max-w-md gap-7"><div className="flex items-center justify-between"><h3 className="text-2xl">A growing idea.</h3><Badge tone="positive">Live demo</Badge></div><NumberTicker value={count} className="font-display text-8xl tracking-tight"/><div className="flex items-center justify-between border-t border-border pt-5"><p className="text-sm text-muted-foreground">People on the list</p><Button variant="outline" onClick={()=>setCount(c=>c+17)}>Add 17 <Plus size={14}/></Button></div></div>;
case 'animated-counter': return <div className="w-full rounded-xl bg-accent p-9 text-foreground md:p-14"><AnimatedCounter target={2048} className="font-display text-7xl tracking-tight md:text-8xl"/><h3 className="mt-6 text-2xl">Small steps. Real progress.</h3><p className="mt-2 text-sm">Counts into view, once you're here.</p></div>;
case 'marquee': return <Marquee><span className="font-display text-4xl">MAKE ROOM.</span><span className="font-display text-4xl">MAKE SOMETHING.</span><span className="font-display text-4xl">MAKE IT YOURS.</span></Marquee>;
case 'scroll-reveal': return <ScrollReveal><Card><h3 className="text-3xl">Here when you arrive.</h3></Card></ScrollReveal>;
case 'stagger-group': return <StaggerGroup className="w-full max-w-md">{['A thought worth keeping.','A shape worth exploring.','Something worth sharing.'].map((t,i)=><div key={t} className="flex items-center gap-5 border-b border-border py-5"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-accent text-lg text-foreground">{i+1}</span><p className="text-lg">{t}</p></div>)}</StaggerGroup>;
case 'magnetic-button': return <MagneticButton>Come a little closer →</MagneticButton>;
case 'tilt-card': return <TiltCard className="w-full max-w-sm border-0 bg-primary p-0 text-primary-foreground"><div className="flex min-h-80 flex-col justify-between p-8"><div className="flex justify-between text-sm"><span>Jez Studio</span><span>↗</span></div><h3 className="text-5xl font-medium leading-[1.05] tracking-tight">A different<br/>perspective.</h3><div className="flex justify-between border-t border-white/30 pt-5 text-xs"><span>Move your pointer.</span><span>Make it yours.</span></div></div></TiltCard>;
case 'spotlight-card': return <SpotlightCard className="w-full max-w-sm border-0 bg-foreground p-8 text-background"><div className="flex min-h-64 flex-col justify-between"><Plus size={32}/><h3 className="text-4xl leading-tight tracking-tight">The detail<br/>is the difference.</h3><p className="text-xs opacity-70">Follow your curiosity. And the light.</p></div></SpotlightCard>;
case 'animated-tabs-indicator': return <AnimatedTabsIndicator items={tabs}/>;
case 'shared-layout-transition': return <SharedLayoutTransition items={[{id:'one',title:'Explore the idea',description:'Open a little space for the unexpected. This panel expands while its neighbours move naturally.'},{id:'two',title:'Find the next step',description:'A small, clear action is often all you need.'}]}/>;
case 'scroll-progress': return <div className="h-96"><ScrollProgress/><h3 className="text-2xl">A sense of where you are.</h3><p className="mt-4 text-sm">The thin line at the top tracks this page as you scroll.</p></div>;
case 'grain-overlay': return <GrainOverlay className="min-h-[360px]"><div className="flex min-h-64 flex-col justify-between"><h3 className="max-w-md font-display text-5xl font-medium leading-[1.03] tracking-tight md:text-6xl">Tactile, by nature.</h3><p className="mt-8 text-sm">A quiet layer of texture.</p></div></GrainOverlay>;
case 'dot-grid': return <DotGrid className="min-h-[360px]"><div className="flex min-h-64 flex-col justify-between"><h3 className="max-w-md font-display text-5xl font-medium leading-[1.03] tracking-tight md:text-6xl">A starting point.</h3><p className="mt-8 text-sm">Space to connect your ideas.</p></div></DotGrid>;
case 'animated-grid': return <AnimatedGrid className="min-h-[360px]"><div className="flex min-h-64 flex-col justify-between"><h3 className="max-w-md font-display text-5xl font-medium leading-[1.03] tracking-tight md:text-6xl">Always in motion.</h3><p className="mt-8 text-sm">An underlying rhythm.</p></div></AnimatedGrid>;
case 'gradient-mesh': return <GradientMesh className="min-h-[360px]"><div className="flex min-h-64 flex-col justify-between"><h3 className="max-w-md font-display text-5xl font-medium leading-[1.03] tracking-tight md:text-6xl">A softer edge.</h3><p className="mt-8 text-sm">Colour, with room to breathe.</p></div></GradientMesh>;
case 'aurora-background': return <AuroraBackground className="min-h-[360px]"><div className="flex min-h-64 flex-col justify-between"><h3 className="max-w-md font-display text-5xl font-medium leading-[1.03] tracking-tight md:text-6xl">After hours.</h3><p className="mt-8 text-sm">A little light in the dark.</p></div></AuroraBackground>;
case 'spotlight-background': return <SpotlightBackground className="min-h-[360px]"><div className="flex min-h-64 flex-col justify-between"><h3 className="max-w-md font-display text-5xl font-medium leading-[1.03] tracking-tight md:text-6xl">Find your focus.</h3><p className="mt-8 text-sm">Let the important things come forward.</p></div></SpotlightBackground>;
case 'border-beam': return <BorderBeam className="min-h-[360px]"><div className="flex min-h-64 flex-col justify-between"><h3 className="max-w-md font-display text-5xl font-medium leading-[1.03] tracking-tight md:text-6xl">Worth a closer look.</h3><p className="mt-8 text-sm">A detail that draws you in.</p></div></BorderBeam>;
case 'ripple-field': return <RippleField/>;
case 'cursor-trail': return <CursorTrail className="min-h-[360px]"><div className="flex min-h-64 flex-col justify-between"><h3 className="max-w-md font-display text-5xl font-medium leading-[1.03] tracking-tight md:text-6xl">Leave your mark.</h3><p className="mt-8 text-sm">Move around. See what follows.</p></div></CursorTrail>;
case 'webgl-particle-field': return <div className="w-full"><WebGLParticleField paused={scenePaused} speed={sceneSpeed} color={sceneColor}/><div className="mt-4 flex flex-wrap items-center justify-between gap-4 text-xs"><button className="rounded-lg border border-border px-3 py-2" onClick={()=>setScenePaused(p=>!p)}>{scenePaused?'Play motion':'Pause motion'}</button><label className="flex items-center gap-2">Palette<select aria-label="Scene palette" className="rounded-lg border border-border bg-background px-2 py-2" value={sceneColor??''} onChange={e=>setSceneColor(e.target.value||undefined)}><option value="">Studio</option><option value="#a6c7cc">Glacier</option><option value="#df9e72">Copper</option><option value="#beb1eb">Iris</option></select></label><label className="flex items-center gap-2">Speed<input aria-label="Scene speed" type="range" min="0" max="2" step="0.1" value={sceneSpeed} onChange={e=>setSceneSpeed(Number(e.target.value))} className="w-20 accent-primary"/></label><span className="text-muted-foreground">Move your pointer to explore</span></div></div>;
case 'webgl-ribbon-field': return <div className="w-full"><WebGLRibbonField paused={scenePaused} speed={sceneSpeed} color={sceneColor}/><div className="mt-4 flex flex-wrap items-center justify-between gap-4 text-xs"><button className="rounded-lg border border-border px-3 py-2" onClick={()=>setScenePaused(p=>!p)}>{scenePaused?'Play motion':'Pause motion'}</button><label className="flex items-center gap-2">Palette<select aria-label="Scene palette" className="rounded-lg border border-border bg-background px-2 py-2" value={sceneColor??''} onChange={e=>setSceneColor(e.target.value||undefined)}><option value="">Studio</option><option value="#a6c7cc">Glacier</option><option value="#df9e72">Copper</option><option value="#beb1eb">Iris</option></select></label><label className="flex items-center gap-2">Speed<input aria-label="Scene speed" type="range" min="0" max="2" step="0.1" value={sceneSpeed} onChange={e=>setSceneSpeed(Number(e.target.value))} className="w-20 accent-primary"/></label><span className="text-muted-foreground">Move your pointer to explore</span></div></div>;
case 'webgl-liquid-surface': return <div className="w-full"><WebGLLiquidSurface paused={scenePaused} speed={sceneSpeed} color={sceneColor}/><div className="mt-4 flex flex-wrap items-center justify-between gap-4 text-xs"><button className="rounded-lg border border-border px-3 py-2" onClick={()=>setScenePaused(p=>!p)}>{scenePaused?'Play motion':'Pause motion'}</button><label className="flex items-center gap-2">Palette<select aria-label="Scene palette" className="rounded-lg border border-border bg-background px-2 py-2" value={sceneColor??''} onChange={e=>setSceneColor(e.target.value||undefined)}><option value="">Studio</option><option value="#a6c7cc">Glacier</option><option value="#df9e72">Copper</option><option value="#beb1eb">Iris</option></select></label><label className="flex items-center gap-2">Speed<input aria-label="Scene speed" type="range" min="0" max="2" step="0.1" value={sceneSpeed} onChange={e=>setSceneSpeed(Number(e.target.value))} className="w-20 accent-primary"/></label><span className="text-muted-foreground">Move your pointer to explore</span></div></div>;
case 'webgl-orb': return <div className="w-full"><WebGLOrb paused={scenePaused} speed={sceneSpeed} color={sceneColor}/><div className="mt-4 flex flex-wrap items-center justify-between gap-4 text-xs"><button className="rounded-lg border border-border px-3 py-2" onClick={()=>setScenePaused(p=>!p)}>{scenePaused?'Play motion':'Pause motion'}</button><label className="flex items-center gap-2">Palette<select aria-label="Scene palette" className="rounded-lg border border-border bg-background px-2 py-2" value={sceneColor??''} onChange={e=>setSceneColor(e.target.value||undefined)}><option value="">Studio</option><option value="#a6c7cc">Glacier</option><option value="#df9e72">Copper</option><option value="#beb1eb">Iris</option></select></label><label className="flex items-center gap-2">Speed<input aria-label="Scene speed" type="range" min="0" max="2" step="0.1" value={sceneSpeed} onChange={e=>setSceneSpeed(Number(e.target.value))} className="w-20 accent-primary"/></label><span className="text-muted-foreground">Move your pointer to explore</span></div></div>;
case 'webgl-terrain': return <div className="w-full"><WebGLTerrain paused={scenePaused} speed={sceneSpeed} color={sceneColor}/><div className="mt-4 flex flex-wrap items-center justify-between gap-4 text-xs"><button className="rounded-lg border border-border px-3 py-2" onClick={()=>setScenePaused(p=>!p)}>{scenePaused?'Play motion':'Pause motion'}</button><label className="flex items-center gap-2">Palette<select aria-label="Scene palette" className="rounded-lg border border-border bg-background px-2 py-2" value={sceneColor??''} onChange={e=>setSceneColor(e.target.value||undefined)}><option value="">Studio</option><option value="#a6c7cc">Glacier</option><option value="#df9e72">Copper</option><option value="#beb1eb">Iris</option></select></label><label className="flex items-center gap-2">Speed<input aria-label="Scene speed" type="range" min="0" max="2" step="0.1" value={sceneSpeed} onChange={e=>setSceneSpeed(Number(e.target.value))} className="w-20 accent-primary"/></label><span className="text-muted-foreground">Move your pointer to explore</span></div></div>;
case 'webgl-image-distortion': return <div className="w-full"><WebGLImageDistortion paused={scenePaused} speed={sceneSpeed} color={sceneColor} imageSrc="/assets/studio-lamp.png"/><div className="mt-4 flex flex-wrap items-center justify-between gap-4 text-xs"><button className="rounded-lg border border-border px-3 py-2" onClick={()=>setScenePaused(p=>!p)}>{scenePaused?'Play motion':'Pause motion'}</button><label className="flex items-center gap-2">Palette<select aria-label="Scene palette" className="rounded-lg border border-border bg-background px-2 py-2" value={sceneColor??''} onChange={e=>setSceneColor(e.target.value||undefined)}><option value="">Studio</option><option value="#a6c7cc">Glacier</option><option value="#df9e72">Copper</option><option value="#beb1eb">Iris</option></select></label><label className="flex items-center gap-2">Speed<input aria-label="Scene speed" type="range" min="0" max="2" step="0.1" value={sceneSpeed} onChange={e=>setSceneSpeed(Number(e.target.value))} className="w-20 accent-primary"/></label><span className="text-muted-foreground">Move your pointer to explore</span></div></div>;
case 'area-chart': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">The bigger picture.</h3><p className="mt-2 text-sm text-muted-foreground">Audience over the last seven days</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><AreaChart/></div>;
case 'line-chart': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">A steady rhythm.</h3><p className="mt-2 text-sm text-muted-foreground">Weekly publishing activity</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><LineChart/></div>;
case 'bar-chart': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">Every day counts.</h3><p className="mt-2 text-sm text-muted-foreground">Orders by day of the week</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><BarChart/></div>;
case 'stacked-bar-chart': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">Better side by side.</h3><p className="mt-2 text-sm text-muted-foreground">This week compared with the last</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><StackedBarChart/></div>;
case 'donut-chart': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">Where it all goes.</h3><p className="mt-2 text-sm text-muted-foreground">A week of studio time</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><DonutChart/></div>;
case 'radial-gauge': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">Almost there.</h3><p className="mt-2 text-sm text-muted-foreground">Progress toward the weekly target</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><RadialGauge/></div>;
case 'heatmap': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">Keep showing up.</h3><p className="mt-2 text-sm text-muted-foreground">A year of small, consistent steps</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><Heatmap/></div>;
case 'sparkline': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">A good direction.</h3><p className="mt-2 text-sm text-muted-foreground">The shape of this week</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><Sparkline/></div>;
case 'live-line-chart': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">In the moment.</h3><p className="mt-2 text-sm text-muted-foreground">A simulated feed, updating live</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><LiveLineChart/></div>;
case 'scatter-chart': return <div className="w-full max-w-2xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-3xl tracking-tight">Find the pattern.</h3><p className="mt-2 text-sm text-muted-foreground">The relationship behind the numbers</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Demo data</span></div><ScatterChart/></div>;
case 'media-aside': return <MediaAside/>;
case 'journal-bento': return <JournalBento/>;
case 'article-sidebar': return <ArticleSidebar/>;
case 'editorial-footer': return <EditorialFooter/>;
case 'studio-footer': return <StudioFooter/>;
case 'newsletter-footer': return <NewsletterFooter/>;
case 'plan-comparison': return <PlanComparison/>;
case 'feature-comparison': return <FeatureComparison/>;
case 'usage-pricing': return <UsagePricing/>;
case 'editorial-hero': return <EditorialHero {...customization}/>;
case 'product-demo-hero': return <ProductDemoHero {...customization}/>;
case 'webgl-hero': return <WebglHero {...customization}/>;
case 'logo-wall': return <LogoWall/>;
case 'feature-grid': return <FeatureGrid/>;
case 'alternating-feature-story': return <AlternatingFeatureStory/>;
case 'product-comparison': return <ProductComparison/>;
case 'metrics-strip': return <MetricsStrip/>;
case 'testimonial-grid': return <TestimonialGrid/>;
case 'testimonial-carousel': return <TestimonialCarousel/>;
case 'pricing-table': return <PricingTable/>;
case 'pricing-comparison': return <PricingComparison/>;
case 'faq': return <Faq/>;
case 'newsletter-signup': return <NewsletterSignup/>;
case 'contact-form': return <ContactForm/>;
case 'cta-section': return <CtaSection/>;
case 'marketing-navigation': return <MarketingNavigation/>;
case 'mega-navigation': return <MegaNavigation/>;
case 'floating-navigation': return <FloatingNavigation/>;
case 'terrain-hero': return <TerrainHero {...customization}/>;
case 'marketing-footer': return <MarketingFooter/>;
case 'particle-hero': return <ParticleHero {...customization}/>;
case 'liquid-hero': return <LiquidHero {...customization}/>;
case 'orb-hero': return <OrbHero {...customization}/>;
case 'silk-hero': return <SilkHero {...customization}/>;
case 'eclipse-hero': return <EclipseHero {...customization}/>;
case 'tunnel-hero': return <TunnelHero {...customization}/>;
case 'constellation-hero': return <ConstellationHero {...customization}/>;
case 'distortion-hero': return <DistortionHero {...customization}/>;
case 'media-hero': return <MediaHero {...customization}/>;
case 'typographic-hero': return <TypographicHero {...customization}/>;
case 'shape-hero': return <ShapeHero {...customization}/>;
case 'studio-hero': return <StudioHero {...customization}/>;
case 'journal-hero': return <JournalHero {...customization}/>;
case 'poster-hero': return <PosterHero {...customization}/>;
case 'portfolio-hero': return <PortfolioHero {...customization}/>;
case 'collage-hero': return <CollageHero {...customization}/>;
case 'editorial-navigation': return <EditorialNavigation/>;
case 'commerce-navigation': return <CommerceNavigation/>;
case 'studio-navigation': return <StudioNavigation/>;
case 'immersive-login': return <ImmersiveLogin {...customization}/>;
case 'ribbon-login': return <RibbonLogin {...customization}/>;
case 'editorial-login': return <EditorialLogin/>;
case 'application-shell': return <ApplicationShell brand="Acme" currentPath="#overview"><div className="mb-7"><p className="mb-2 text-xs text-muted-foreground">Tuesday, 8 September</p><h2 className="font-display text-2xl">Good morning, Alex.</h2><p className="mt-2 text-sm text-muted-foreground">Here’s what needs your attention.</p></div><div className="grid gap-6 xl:grid-cols-[1.3fr_1fr]"><div><h3 className="mb-4 text-sm font-semibold">Your tasks</h3><TaskList/></div><ActivityFeed/></div></ApplicationShell>;
case 'workspace-navigation': return <WorkspaceNavigation/>;
case 'analytics-overview': return <AnalyticsOverview/>;
case 'activity-feed': return <ActivityFeed/>;
case 'searchable-records-screen': return <SearchableRecordsScreen/>;
case 'record-detail-panel': return <RecordDetailPanel/>;
case 'kanban-board': return <KanbanBoard/>;
case 'task-list': return <TaskList/>;
case 'calendar-schedule': return <CalendarSchedule/>;
case 'onboarding-wizard': return <OnboardingWizard/>;
case 'sign-in-form': return <SignInForm/>;
case 'sign-up-form': return <SignUpForm/>;
case 'password-reset-form': return <PasswordResetForm/>;
case 'profile-settings': return <ProfileSettings/>;
case 'team-management': return <TeamManagement/>;
case 'billing-settings': return <BillingSettings/>;
case 'notification-centre': return <NotificationCentre/>;
case 'command-search': return <CommandSearch/>;
case 'chat-workspace': return <ChatWorkspace/>;
case 'workspace-sidebar': return <WorkspaceSidebar/>;
case 'rail-sidebar': return <RailSidebar/>;
case 'inset-sidebar': return <InsetSidebar/>;
case 'user-switcher': return <UserSwitcher/>;
case 'organization-switcher': return <OrganizationSwitcher/>;
case 'sso-login': return <SSOLogin {...customization}/>;
case 'split-login': return <SplitLogin {...customization}/>;
case 'workspace-login': return <WorkspaceLogin {...customization}/>;default:return <p>Example not found.</p>}}return <Suspense fallback={<p className="p-8 text-sm">Loading example…</p>}><div className="w-full min-w-0">{render()}{notice&&<p role="status" className="mt-4 text-sm">{notice}</p>}</div></Suspense>}